autoload -Uz compinit
fpath+=~/.zfunc
compinit

HIST_STAMPS="mm/dd/yyyy"

bindkey -v

PROMPT='%W %T %n@%m %d > '
export PATH="$PATH:$HOME/.local/bin"

function randir()
{
  TMP_DIR=$(mktemp -d)
  pushd $TMP_DIR
}

tmks() {
  tmux kill-session -t $(tmux ls | fzf | cut -d' ' -f 1)
}

tma() {
  tmux a -t $(tmux ls | fzf | cut -d' ' -f 1)
}

alias rzsh="source ~/.zshrc"

alias gr="git r -v"
alias grs="git rs"
alias grsh="git rs --hard"
alias gb="git b"
alias gco="git co"
alias gc="git c"
alias gd="git d"
alias gsw="git sw"
alias gl="git l"
alias gst="git st"
alias gps="git ps"
alias gpsf="git ps --force-with-lease"
alias gf="git fetch"
alias grb="git rebase"

# Create a random temp dir and navigate to it.
function rndd() {
    DIR=$(mktemp -d)
    pushd $DIR
}

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000000
SAVEHIST=10000000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

source <(fzf --zsh)

eval "$(scmpuff init -s)"
